export const MILLISECONDS_PER_SECOND = 1000;
export const SECONDS_PER_MINUTE = 60;
export const MINUTES_PER_HOUR = 60;
export const HOURS_PER_DAY = 24;
export const DAYS_PER_WEEK = 7;
export const DAYS_PER_MONTH = 30;

export const SESSION_LIFETIME =
  MILLISECONDS_PER_SECOND *
  SECONDS_PER_MINUTE *
  MINUTES_PER_HOUR *
  HOURS_PER_DAY *
  DAYS_PER_MONTH;

export const SESSION_REFRESH_TIME = SESSION_LIFETIME / 2;
export const SESSION_COOKIE_NAME = "session";

export const DATATABLE_PAGE_SIZE = 15;
