/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as MainContactRouteImport } from './routes/_main/contact'
import { Route as MainLoginRouteImport } from './routes/_main/login'
import { Route as MainShopRouteImport } from './routes/_main/shop'
import { Route as MainSignupRouteImport } from './routes/_main/signup'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminContactEntriesRouteImport } from './routes/admin/contact-entries'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductCategoriesRouteImport } from './routes/admin/product-categories'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as AdminProductCategoriesNewRouteImport } from './routes/admin/product-categories_.new'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products_.new'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users_.$id'
import { Route as AdminUsersNewRouteImport } from './routes/admin/users_.new'
import { Route as ApiPublicSplatRouteImport } from './routes/api.public.$'
import { Route as AdminProductCategoriesIdEditRouteImport } from './routes/admin/product-categories_.$id.edit'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products_.$id.edit'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainContactRoute = MainContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLoginRoute = MainLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainShopRoute = MainShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSignupRoute = MainSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => MainRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactEntriesRoute = AdminContactEntriesRouteImport.update({
  id: '/contact-entries',
  path: '/contact-entries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductCategoriesRoute = AdminProductCategoriesRouteImport.update({
  id: '/product-categories',
  path: '/product-categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductCategoriesNewRoute =
  AdminProductCategoriesNewRouteImport.update({
    id: '/product-categories_/new',
    path: '/product-categories/new',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users_/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/users_/new',
  path: '/users/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/api/public/$',
  path: '/api/public/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductCategoriesIdEditRoute =
  AdminProductCategoriesIdEditRouteImport.update({
    id: '/product-categories_/$id/edit',
    path: '/product-categories/$id/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products_/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof MainAboutRoute
  '/contact': typeof MainContactRoute
  '/login': typeof MainLoginRoute
  '/shop': typeof MainShopRoute
  '/signup': typeof MainSignupRoute
  '/admin/contact-entries': typeof AdminContactEntriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/product-categories': typeof AdminProductCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/upload': typeof ApiUploadRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/product-categories/new': typeof AdminProductCategoriesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/admin/product-categories/$id/edit': typeof AdminProductCategoriesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/contact': typeof MainContactRoute
  '/login': typeof MainLoginRoute
  '/shop': typeof MainShopRoute
  '/signup': typeof MainSignupRoute
  '/admin/contact-entries': typeof AdminContactEntriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/product-categories': typeof AdminProductCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/upload': typeof ApiUploadRoute
  '/': typeof MainIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/product-categories/new': typeof AdminProductCategoriesNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/admin/product-categories/$id/edit': typeof AdminProductCategoriesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/contact': typeof MainContactRoute
  '/_main/login': typeof MainLoginRoute
  '/_main/shop': typeof MainShopRoute
  '/_main/signup': typeof MainSignupRoute
  '/admin/contact-entries': typeof AdminContactEntriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/product-categories': typeof AdminProductCategoriesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/upload': typeof ApiUploadRoute
  '/_main/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/product-categories_/new': typeof AdminProductCategoriesNewRoute
  '/admin/products_/new': typeof AdminProductsNewRoute
  '/admin/users_/$id': typeof AdminUsersIdRoute
  '/admin/users_/new': typeof AdminUsersNewRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/admin/product-categories_/$id/edit': typeof AdminProductCategoriesIdEditRoute
  '/admin/products_/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/login'
    | '/shop'
    | '/signup'
    | '/admin/contact-entries'
    | '/admin/orders'
    | '/admin/product-categories'
    | '/admin/products'
    | '/admin/users'
    | '/api/upload'
    | '/admin/'
    | '/admin/product-categories/new'
    | '/admin/products/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/api/public/$'
    | '/admin/product-categories/$id/edit'
    | '/admin/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/login'
    | '/shop'
    | '/signup'
    | '/admin/contact-entries'
    | '/admin/orders'
    | '/admin/product-categories'
    | '/admin/products'
    | '/admin/users'
    | '/api/upload'
    | '/'
    | '/admin'
    | '/admin/product-categories/new'
    | '/admin/products/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/api/public/$'
    | '/admin/product-categories/$id/edit'
    | '/admin/products/$id/edit'
  id:
    | '__root__'
    | '/_main'
    | '/admin'
    | '/_main/about'
    | '/_main/contact'
    | '/_main/login'
    | '/_main/shop'
    | '/_main/signup'
    | '/admin/contact-entries'
    | '/admin/orders'
    | '/admin/product-categories'
    | '/admin/products'
    | '/admin/users'
    | '/api/upload'
    | '/_main/'
    | '/admin/'
    | '/admin/product-categories_/new'
    | '/admin/products_/new'
    | '/admin/users_/$id'
    | '/admin/users_/new'
    | '/api/public/$'
    | '/admin/product-categories_/$id/edit'
    | '/admin/products_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/contact': {
      id: '/_main/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MainContactRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/shop': {
      id: '/_main/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof MainShopRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/signup': {
      id: '/_main/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof MainSignupRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contact-entries': {
      id: '/admin/contact-entries'
      path: '/contact-entries'
      fullPath: '/admin/contact-entries'
      preLoaderRoute: typeof AdminContactEntriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/product-categories': {
      id: '/admin/product-categories'
      path: '/product-categories'
      fullPath: '/admin/product-categories'
      preLoaderRoute: typeof AdminProductCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/product-categories_/new': {
      id: '/admin/product-categories_/new'
      path: '/product-categories/new'
      fullPath: '/admin/product-categories/new'
      preLoaderRoute: typeof AdminProductCategoriesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products_/new': {
      id: '/admin/products_/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users_/$id': {
      id: '/admin/users_/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users_/new': {
      id: '/admin/users_/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/api/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/product-categories_/$id/edit': {
      id: '/admin/product-categories_/$id/edit'
      path: '/product-categories/$id/edit'
      fullPath: '/admin/product-categories/$id/edit'
      preLoaderRoute: typeof AdminProductCategoriesIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products_/$id/edit': {
      id: '/admin/products_/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainContactRoute: typeof MainContactRoute
  MainLoginRoute: typeof MainLoginRoute
  MainShopRoute: typeof MainShopRoute
  MainSignupRoute: typeof MainSignupRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainContactRoute: MainContactRoute,
  MainLoginRoute: MainLoginRoute,
  MainShopRoute: MainShopRoute,
  MainSignupRoute: MainSignupRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminContactEntriesRoute: typeof AdminContactEntriesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductCategoriesRoute: typeof AdminProductCategoriesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductCategoriesNewRoute: typeof AdminProductCategoriesNewRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminProductCategoriesIdEditRoute: typeof AdminProductCategoriesIdEditRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContactEntriesRoute: AdminContactEntriesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductCategoriesRoute: AdminProductCategoriesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductCategoriesNewRoute: AdminProductCategoriesNewRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminProductCategoriesIdEditRoute: AdminProductCategoriesIdEditRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  ApiPublicSplatRoute: ApiPublicSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
